In [1]:
import numpy as np 
import pandas as pd 
df = pd.read_csv('placement.csv')
df.head()

,student_id,cgpa,attendance,iq,internships,branch,placement,package_lpa
0,STU001,8.6,92.0,128.0,2.0,CSE,Placed,8.5
1,STU002,7.4,78.0,105.0,1.0,IT,Placed,5.2
2,STU003,6.8,71.0,98.0,0.0,ECE,Not Placed,0.0
3,STU004,9.1,95.0,135.0,3.0,CSE,Placed,12.0
4,STU005,7.9,84.0,112.0,1.0,IT,Placed,6.4

In [2]:
df= df.iloc[:,5:7]
df.head()

  branch   placement
0    CSE      Placed
1     IT      Placed
2    ECE  Not Placed
3    CSE      Placed
4     IT      Placed

In [4]:
x=df.iloc[:,0:1]
y=df.iloc[:,-1]
print(x.head())
print(y.head())

  branch
0    CSE
1     IT
2    ECE
3    CSE
4     IT
0        Placed
1        Placed
2    Not Placed
3        Placed
4        Placed
Name: placement, dtype: str

In [14]:
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
oe = OrdinalEncoder(categories=[['CSE','IT','ECE','CE','ME']])
x_train = oe.fit_transform(x_train)
x_test=oe.transform(x_test)

le= LabelEncoder()
y_train= le.fit_transform(y_train)
y_test=le.transform(y_test)
print(x_train[:5])
print(x_test[:5])
print(y_train[:5])
print(y_test[:5])

[[2.]
 [0.]
 [1.]
 [1.]
 [1.]]
[[0.]
 [4.]
 [3.]
 [2.]
 [0.]]
[1 1 1 1 1]
[1 0 1 1 1]