In [7]:
import numpy as np 
import pandas as pd 
import seaborn as sns
flights = sns.load_dataset('flights')
print(flights.sample())

    year month  passengers
91  1956   Aug         405

In [8]:
flights['year'].count()

np.int64(144)

In [9]:
flights['year'].unique()

array([1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959,
       1960])

In [10]:
#one hot encoding using pandas
flights=pd.get_dummies(flights,columns=['month'],dtype=int, drop_first=True) 
#drop-first = helps to drop first coln after encoding so that we don't get multicollinarity 
flights

,year,passengers,month_Feb,month_Mar,month_Apr,month_May,month_Jun,month_Jul,month_Aug,month_Sep,month_Oct,month_Nov,month_Dec
0,1949,112,0,0,0,0,0,0,0,0,0,0,0
1,1949,118,1,0,0,0,0,0,0,0,0,0,0
2,1949,132,0,1,0,0,0,0,0,0,0,0,0
3,1949,129,0,0,1,0,0,0,0,0,0,0,0
4,1949,121,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,1960,606,0,0,0,0,0,0,1,0,0,0,0
140,1960,508,0,0,0,0,0,0,0,1,0,0,0
141,1960,461,0,0,0,0,0,0,0,0,1,0,0
142,1960,390,0,0,0,0,0,0,0,0,0,1,0
143,1960,432,0,0,0,0,0,0,0,0,0,0,1

In [11]:
# so pandas give differnt colns order every time let say i re run toh mard feb may aye asa krke so model train kerte hue we use sklearn only

In [12]:
#onehot encoding using sklearn
flights= sns.load_dataset('tips')
print(flights.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
from sklearn.model_selection import train_test_split
x= flights.iloc[:,0:5]
y=flights.iloc[:,5]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train[:5])
print(y_test[:5])

     total_bill   tip   sex smoker   day
228       13.28  2.72  Male     No   Sat
208       24.27  2.03  Male    Yes   Sat
96        27.28  4.00  Male    Yes   Fri
167       31.71  4.50  Male     No   Sun
84        15.98  2.03  Male     No  Thur
24     Dinner
6      Dinner
153    Dinner
211    Dinner
198     Lunch
Name: time, dtype: category
Categories (2, str): ['Lunch', 'Dinner']

In [16]:
# fo x train m bhut colns hoge jinper encoding nhi lagni hogi right so we will apply on column we need to apply then merge then get x_train
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first' , dtype=int) # sparse = false kerne sei .toarray() nhi kerna pdega
#dtype sei encoded value 0,1 m hogi verna true false ati h 
x_train_new = ohe.fit_transform(x_train[['sex','smoker','day']]).toarray() # like this i will apply on particulars colns jha lagan 
x_test_new=ohe.transform(x_train[['sex','smoker','day']]).toarray()

np.hstack((x_train[['total_bill','tip']].values , x_train_new))

#new bhi array tha and .values krke toh humne hstack kerke sath ker dia

array([[13.28,  2.72,  1.  , ...,  1.  ,  0.  ,  0.  ],
       [24.27,  2.03,  1.  , ...,  1.  ,  0.  ,  0.  ],
       [27.28,  4.  ,  1.  , ...,  0.  ,  0.  ,  0.  ],
       ...,
       [ 5.75,  1.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [34.63,  3.55,  1.  , ...,  0.  ,  1.  ,  0.  ],
       [44.3 ,  2.5 ,  0.  , ...,  1.  ,  0.  ,  0.  ]], shape=(195, 7))

In [19]:
flights['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [20]:
# here we have only 2 category but still if we have many category then we can use the most frequent one only 
counts=flights['time'].value_counts()
replace=counts[counts<=100].index

In [24]:
new_time = flights['time'].astype(str).replace(replace, 'others')

pd.get_dummies(new_time, dtype=int).sample(10)

     Dinner  others
91        1       0
20        1       0
152       1       0
46        1       0
201       0       1
86        0       1
147       0       1
0         1       0
235       1       0
233       1       0

In [ ]:
flights['time'] = flights['time'].astype(str).replace(
    replace,
    'others'
)

flights.head()
flights = pd.get_dummies(
    flights,
    columns=['time'],
    dtype=int
)