In [3]:
import pandas as pd 
data = pd.read_csv('placement.csv')

1.How big the data?

In [5]:
data.shape

(60, 8)

2.How does daat look like

In [7]:
data.sample(5) # 5 random rows

,student_id,cgpa,attendance,iq,internships,branch,placement,package_lpa
24,STU025,7.5,79.0,106.0,1.0,CSE,Placed,5.5
12,STU013,5.8,59.0,84.0,0.0,ME,Not Placed,0.0
45,STU046,8.8,91.0,131.0,3.0,ECE,Placed,9.0
30,STU031,8.3,88.0,122.0,2.0,CSE,Placed,7.9
55,STU056,6.9,72.0,97.0,0.0,CE,Not Placed,NaN

3.what type of cols

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   60 non-null     str
 1   cgpa         58 non-null     float64
 2   attendance   58 non-null     float64
 3   iq           59 non-null     float64
 4   internships  59 non-null     float64
 5   branch       60 non-null     str
 6   placement    60 non-null     str
 7   package_lpa  59 non-null     float64
dtypes: float64(5), str(3)
memory usage: 3.9 KB

In [ ]:
4.are there any missing values

In [9]:
data.isnull().sum()

student_id     0
cgpa           2
attendance     2
iq             1
internships    1
branch         0
placement      0
package_lpa    1
dtype: int64

In [ ]:
5.how does the data look mathematically

In [10]:
data.describe()

            cgpa  attendance          iq  internships  package_lpa
count  58.000000   58.000000   59.000000    59.000000    59.000000
mean    7.510345   79.500000  108.728814     1.237288     9.164407
std     1.241630   12.247807   19.100307     1.222476    32.157134
min     2.100000   35.000000   40.000000     0.000000     0.000000
25%     6.800000   71.250000   96.500000     0.000000     0.000000
50%     7.600000   81.500000  108.000000     1.000000     5.900000
75%     8.375000   88.750000  121.500000     2.000000     7.850000
max    10.000000   99.000000  150.000000     5.000000   250.000000

6. are the duplicte values

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
#correlation of cols
data.corr()
data.correlation.

ValueError: could not convert string to float: 'STU001'